### ISSUE TITLE
dupeAndShift interacts weirdly with re-binning

### ISSUE THREAD

**Issue by mattperich** [limblab/TrialData#2]
Basically, if you re-bin with truncateAndBin AFTER dupeAndShift, everything is screwed up. Will need to add a section to truncateAndBin that looks for _shift fields and rebins them accordingly (if that makes sense... otherwise, just automatically deletes the field and calls dupeAndShift again with the rebinned data).

**Comment by raeedcho** [comment]
This is super old, but is this just a problem with truncateAndBin, or does it also affect trimTD and binTD?

If this isn't an issue anymore, let's close it.

**Comment by mattperich** [comment]
As far as I've seen, binTD/trimTD and dupeAndShift work well together in any order. However, just to note, remember that you lose bins of time when you dupeAndShift due to the non-overlapping segments so it's often best to dupeAndShift before the final trimTD call.

I am closing this issue now.
