### ISSUE TITLE
reorderTDfields doesn't work well for 'vel_shift'

### ISSUE THREAD

**Issue by juangallego** [limblab/TrialData#6]
After doing 'dupeAndShift' of 'vel' the new 'vel_shift' appears in different places in the structure… and its placing doesn't seem consistent

**Comment by mattperich** [comment]
Fixed! All _spikes fields will now be sorted to appear after their parent field after a call to reorderTDfields. Note: It's not the most elegant code (any intrepid coders who want to write a more clever solution, feel free!) but it seems to work.
